language: haskell
dist: trusty

cabal: "2.4"

matrix:
  include:
    - ghc: "8.6.3"  
    - ghc: "8.4.4"
    - ghc: "8.2.2"
    - ghc: "8.0.2"
    - ghc: "7.10.3"
    - ghc: "7.8.4"
    - ghc: "7.6.3"
    - ghc: "7.4.2"
    - ghc: "7.0.4"

#before_install:
# - set
# - update-alternatives --display opt-ghc
# - update-alternatives --list opt-ghc
# - update-alternatives --display opt-cabal

#install:
# - set
# - ls -l /opt/ghc/
# - ls -l /opt/ghc/bin
# - ls -l /opt/cabal/
# - ghc --version
# - which ghc

install:

script:
# - cabal update
 - cabal new-build
 - cabal new-test --enable-test

# - update-alternatives --display opt-ghc
# - update-alternatives --list opt-ghc
