language: haskell
dist: trusty

cabal: "2.0"

matrix:
  include:
    - ghc: "8.2.1"
    - ghc: "8.0.2"
    - ghc: "7.10.3"
    - ghc: "7.8.4"
    - ghc: "7.6.3"

before_install:
# - set
 - update-alternatives --display opt-ghc
 - update-alternatives --list opt-ghc
 - update-alternatives --display opt-cabal

install:
# - set
 - ls -l /opt/ghc/
 - ls -l /opt/ghc/bin
 - ls -l /opt/cabal/
 - ghc --version
 - which ghc

 - update-alternatives --display opt-ghc
 - update-alternatives --list opt-ghc
